name: README builder
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v1
        
      - name: Install packages
        run: npm install
        
      - name: (Re)build README
        run: npm run build > README.md
        
      - name: Configure git
        run: |
          git config --global user.email "qmacro-bot@example.com"
          git config --global user.name "qmacro bot"
        
      - name: Commit README changes
        run: |
          git add README.md
          git commit -m 'update README' || exit 0
          git push
